# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_remove_worldborder_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldborder',
            options={'ordering': ['name']},
        ),
    ]
